apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-minikube-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MohamedHamdy120/devops-minikube-project.git
    targetRevision: main
    path: gitops/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
